status:
  enabled: true

proxy:
  # Enable creating a Kubernetes service for the proxy
  type: NodePort #ClusterIP # LoadBalancer does not work with kind
  
  ingress:
    # Enable/disable exposure using ingress.
    enabled: false # true causing errors

  http:
    # Enable plaintext HTTP listen for the proxy
    enabled: true
    # Set a nodePort which is available if service type is NodePort
    nodePort: 32080

  tls:
    # Enable HTTPS listen for the proxy
    enabled: true
    # Set a nodePort which is available if service type is NodePort
    nodePort: 32443

serviceMonitor:
  # Specifies whether ServiceMonitor for Prometheus operator should be created
  # If you wish to gather metrics from a Kong instance with the proxy disabled (such as a hybrid control plane), see:
  # https://github.com/Kong/charts/blob/main/charts/kong/README.md#prometheus-operator-integration
  enabled: true
  # interval: 10s
  # Specifies namespace, where ServiceMonitor should be installed
  namespace: kong
  # labels:
  #   foo: bar
  # targetLabels:
  #   - foo

  # honorLabels: false
  # metricRelabelings: []
